In [1]:
import numpy as np
import cv2


In [2]:
img = cv2.imread('./images/3_cars.jpg') #bgr

In [3]:
cv2.imshow('orginal_image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
img.shape

(795, 1200, 3)

In [5]:
b,g,r = cv2.split(img)

In [6]:
print(b)

[[43 33 36 ... 19 27 39]
 [28 12 11 ...  2  7 20]
 [28 15 16 ...  3 12 25]
 ...
 [60 49 48 ... 27 33 43]
 [58 48 47 ... 27 33 43]
 [75 64 63 ... 44 50 60]]


In [7]:
b.shape, g.shape, r.shape

((795, 1200), (795, 1200), (795, 1200))

In [8]:
cv2.imshow('blue image', b)
cv2.imshow('green image',g)
cv2.imshow('red image',r)
cv2.imshow('orginal', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Convert Color

In [9]:
img1 = cv2.imread('./images/beach.jpg')

In [10]:
cv2.imshow('orginal-bgr', img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# BGR to Gray
gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)

# BGR to RGB
img_rgb = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)

# BGR to HSV
img_hsv = cv2.cvtColor(img1, cv2.COLOR_BGR2HSV)


# BGR to LAB
img_lab = cv2.cvtColor(img1, cv2.COLOR_BGR2Lab)

cv2.imshow('orginal image', img1)
cv2.imshow('Gray scale', gray)
cv2.imshow('RGB scale', img_rgb)
cv2.imshow('HSB scale', img_hsv)
cv2.imshow('LAB scale', img_lab)

cv2.waitKey(0)
cv2.destroyAllWindows()