In [2]:
import numpy as np
import cv2

Face Detection

In [2]:
img = cv2.imread('./images/0021.jpg')
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# load cascasde classfiere - frontalface
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

In [5]:
# apply cascade classfier to an image
faces, num_detection = face_cascade.detectMultiScale2(img)

In [6]:
print(faces)

[[114  40 196 196]]


In [7]:
print(num_detection)

[89]


In [17]:
pt1 = (114, 40)
pt2 = (114+196, 40+196)
#  draw the rectangle
cv2.rectangle(img, pt1, pt2, (0, 255,0))
cv2.imshow('face detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# draw the circle
cx =114 + 196 // 2
cy = 40 + 196 // 2
r = 196 //2

cv2.circle(img, (cx,cy), r, (0,255,255), 2)
cv2.imshow('face detection circle', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
imgh = cv2.imread('./images/hasib.jpg')
cv2.imshow('hasib',imgh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
facesh, num_detection_hasib = face_cascade.detectMultiScale2(imgh)

In [14]:
print(facesh)

[[ 71  67 162 162]]


In [28]:
pt1 = (71, 67)
pt2 = (71+162, 67+162)

#  draw the rectangle
cv2.rectangle(imgh, pt1, pt2, (0, 255,0))
cv2.imshow('face detection Hasib',imgh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
cx =71 + 162 // 2
cy = 67 + 162 // 2
r = 196 //2

cv2.circle(imgh, (cx,cy), r, (0,0,255), 2)
cv2.imshow('face detection circle', imgh)
cv2.waitKey(0)
cv2.destroyAllWindows()

Multiple Face Detection

In [3]:
img = cv2.imread('./images/friends.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

# step-1 apply cascade classifier to an image
faces, num_detection = face_cascade.detectMultiScale2(img, minNeighbors=8)

# step-2: run a loop

for x,y,w,h in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,255))

# step-3 display the image
cv2.imshow('facedetection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(faces)

[[128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]


In [6]:
print(num_detection)

[  4   4 104  84  71]


Faces & Eyes Detection

In [9]:
img = cv2.imread('./images/friends.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')

In [12]:
# step -1: Face Detection
faces, num_detection_face = face_cascade.detectMultiScale2(img, minNeighbors=8)
for x,y,w,h in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0))

    # step -2 croping the face

    face_roi = img[y:y+h, x:x+h] #croping the image

    # step -3 apply to cascade classifier (eye)
    eyes, num_detection_eyes = eye_cascade.detectMultiScale2(face_roi)

    for ex, ey, ew, eh in eyes:
        cx =x + ex+ew//2
        cy = y + ey +eh // 2
        r = eh //2
        cv2.circle(img, (cx, cy), r, (255,0,255),2)

# step -3
cv2.imshow('face eye detection', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Faces, Eyes, Smiles Detection

In [13]:
img = cv2.imread('./images/friends.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')
smile_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_smile.xml')

# step -1: Face Detection
faces, num_detection_face = face_cascade.detectMultiScale2(img, minNeighbors=8)
for x,y,w,h in faces:
    face_roi = img[y:y+h, x:x+h].copy() #croping the image
    cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0))

    

    

    # step -2 apply to cascade classifier (eye)
    eyes, num_detection_eyes = eye_cascade.detectMultiScale2(face_roi)

    for ex, ey, ew, eh in eyes:
        cx =x + ex+ew//2
        cy = y + ey +eh // 2
        r = eh //2
        cv2.circle(img, (cx, cy), r, (255,0,255),2)
    
    # step 3 smile detection
    smiles, num_detection_smile = smile_cascade.detectMultiScale2(face_roi)
    for sx, sy, sw, sh in smiles:
        cv2.rectangle(img, (x + sx, y + sy), (x+sx+sw, y+sy+sh), (255,0,0),2)



# step -3
cv2.imshow('face eye smail detection', img)
cv2.waitKey(0)
cv2.destroyAllWindows()